DjangoOne_Users/DjangoOne_Users/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from UserAPP import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'userapp/',include('UserAPP.urls')),
    url(r'^logout/', views.user_logout,name='logout'),
    url(r'^special/', views.special,name='special'),

]

DjangoOne_Users/UserAPP/urls.py
from django.conf.urls import url
from .import views

app_name = 'userapp'

urlpatterns=[
  url(r'users/',views.users,name='users'),
  url(r'signup/',views.signup,name='signup'),
  url(r'register/',views.register,name='register'),
  url(r'user_login/',views.user_login,name='user_login'),

]

DjangoOne_Users/UserAPP/models.py
from django.db import models
from django.contrib.auth.models import User as adminuser

# Create your models here.

class User(models.Model):
    FirstName = models.CharField(max_length=264)
    LastName = models.CharField(max_length=264)
    Email = models.CharField(max_length=264,unique=True)


class UserProfileInfo(models.Model):

    user = models.OneToOneField(adminuser)

    # additional attributes
    portfolio_site= models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

DjangoOne_Users/UserAPP/forms.py
from django import forms
from UserAPP.models import User

class UserForm(forms.ModelForm):
      class Meta:
          model=User
          fields = "__all__"

DjangoOne_Users/UserAPP/views.py
from django.shortcuts import render
from UserAPP.models import User
from .import forms, loginform
#Login imports
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'UserAPP/index.html',context=context_dict)

@login_required
def special(request):
    return HttpResponse("You are Logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def users(request):
    users_list = User.objects.order_by('FirstName')
    userslist = {'list':users_list}
    return render(request,'UserAPP/userlist.html',context = userslist)

def signup(request):
    form= forms.UserForm()

    if request.method == 'POST':
        form=forms.UserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return users(request)
        else:
            print("Form invalid!")

    return render(request,'UserAPP/signup.html',{'form':form})

def register(request):

    registered=False

    if request.method == 'POST':

        user_form=loginform.UserForm(data=request.POST)
        profile_form = loginform.UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form= loginform.UserForm()
        profile_form = loginform.UserProfileForm()

    return render(request,'UserAPP/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not active")
        else:
            print("Login Failed !")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("Invalid Login Details !")

    else:
        return render(request,'UserAPP/login.html', {})

DjangoOne_Users/templates/UserAPP/base.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "css/userapp.css" %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" /> -->
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="#">BRAND</a> </li>
          <li> <a class="navbar-link" href="{% url 'userapp:users' %}">Users</a> </li>
          <li> <a class="navbar-link" href="{% url 'userapp:signup' %}">Signup</a> </li>
          <li> <a class="navbar-link" href="{% url 'userapp:register' %}">Register</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'index' %}">Home</a> </li>
          {% if user.is_authenticated %}
          <li> <a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class="navbar-link" href="{% url 'userapp:user_login' %}">Login</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Code -->
      {% endblock %}

    </div>

  </body>
</html>

DjangoOne_Users/templates/UserAPP/index.html
<!DOCTYPE html>

{% extends "UserAPP/base.html" %}
{% load my_extras %}
  {% block body_block %}
      <div class="jumbotron">
       <h1>Welcome to the Home Page </h1>
       <a href="{% url 'userapp:users' %}">Please go to /users to get the list of users !</a>
       <br/><a href="{% url 'userapp:signup' %}">Please go to /signup to register! </a>
       <br/><a href="{% url 'admin:index' %}">Link to Admin</a>
       <br/><a href="{% url 'index' %}">Home Page</a>
      <br/> {{text|cutout:'world'}}
      <br/> {{number|add:"99"}}
  {% endblock %}

DjangoOne_Users/templates/UserAPP/login.html
<!DOCTYPE html>
{% extends "UserAPP/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
        <h1> Please Login !</h1>
      <form action="{% url 'userapp:user_login' %}" method="POST">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Enter username">
          <label for="password">Password:</label>
          <input type="password" name="password">
          <input type="submit" class="btn btn-primary" value="Login">
       </form>
    </div>
  {% endblock %}

DjangoOne_Users/templates/UserAPP/registration.html
<!DOCTYPE html>
{% extends "UserAPP/base.html" %}
  {% block body_block %}
    <div class="container">
      {%if registered%}
        <h1> Thank you for Registering !</h1>
      {% else %}
      <h1>Register Here!</h1>
      <h3>Fill out the Form: </h3> <br/>
      <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
           {{user_form.as_p}}
           {{profile_form.as_p}}
           <input type="submit" class="btn btn-primary" value="submit">
       </form>
       {% endif %}
    </div>
  {% endblock %}

DjangoOne_Users/templates/UserAPP/signup.html
<!DOCTYPE html>
{% extends "UserAPP/base.html" %}
  {% block body_block %}
    <h1> Fill out the form!</h1>
    <div class="container">
      <form method="POST">
           {{form.as_p}}
           {% csrf_token %}
           <input type="submit" class="btn btn-primary" value="submit">
       </form>
    </div>
  {% endblock %}

DjangoOne_Users/templates/UserAPP/userlist.html
<!DOCTYPE html>

{% extends "UserAPP/base.html" %}
  {% block body_block %}
    <h2> List of users!</h2>
    <div class="container">
      {% if list %}

      <table>
        <thead>
          <th>FirstName</th>
          <th>LastName</th>
          <th>Email</th>
        </thead>

        {% for acc in list %}

        <tr>
          <td>{{acc.FirstName}}</td>
          <td>{{acc.LastName}}</td>
          <td>{{acc.Email}}</td>
        </tr>

        {% endfor %}

      </table>

      {% else %}
      <p>No Users Found !</p>
      {% endif %}

    </div>
  {% endblock %}